include:
  - local: /.gitlab-ci/test.gitlab-ci.yml
  - local: /.gitlab-ci/package.gitlab-ci.yml
  - local: /.gitlab-ci/build.gitlab-ci.yml
  - local: /.gitlab-ci/checkout.gitlab-ci.yml
  - local: /.gitlab-ci/deploy.gitlab-ci.yml
  # - local: /.gitlab-ci/example.gitlab-ci.yml

.alpine-base:
  image: alpine:3.16

.aws-base:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

.mvn-base:
  image: maven:3-jdk-11

.ssh:
  extends: .alpine-base
  before_script:
    - apk update && apk add openssh
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo $SECRET_ENV_EC2_PUBLIC_IP_ADDRESS
    - ssh-keyscan $SECRET_ENV_EC2_PUBLIC_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 0400 key_pair.pem
    # - chmod 0400 main.pem

stages:
  - Test
  - Package
  - Build
  - Checkout
  - Deploy
# stages:
#   - Example
#   - ExampleDeploy
