stages:
  - build
  - package

build:
  image: alpine
  stage: build
  script:
    - echo "Hello World" > index.html
  artifacts:
    paths:
      - index.html

build docker image:
  image: docker
  stage: package
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - docker-compose up
    - docker-compose ls
    - docker-compose push --all-tags $CI_REGISTRY_IMAGE
