stages:
  - build
  - package

build:
  image: alpine
  stage: build
  script:
    - echo "Hello World" > index.html
  artifacts:
    paths:
      - index.html

build docker image:
  image: docker
  stage: package
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker image ls
    - docker push --all-tags $CI_REGISTRY_IMAGE
