stages:
  - build
  - package

build:
  image: alpine
  stage: build
  script:
    - echo "Hello World" > index.html
  artifacts:
    paths:
      - index.html

build docker image:
  image: docker
  stage: package
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - echo "Logging into ${CI_REGISTRY}"
    - docker login --username gitlab-ci-token --password "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker images
    - docker run -d -p 8080:8080 --name $CI_REGISTRY_IMAGE --entrypoint /app/src/main/resources/run.sh $CI_REGISTRY_IMAGE
    - docker push --all-tag $CI_REGISTRY_IMAGE
