stages:
  - build
  - package

build:
  image: alpine
  stage: build
  script:
    - echo "Hello World" > index.html
  artifacts:
    paths:
      - index.html

build docker image:
  image: docker
  stage: package
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 772962499539.dkr.ecr.ap-southeast-1.amazonaws.com
  script:
    - docker-compose up
    - docker-compose ls
    - docker-compose push --all-tags $CI_REGISTRY_IMAGE
