version: "2.1"

services:
  reno:
    container_name: "reno"
    build:
      dockerfile: Dockerfile-dev
      context: .
    ports:
      - "9099:8080"
    depends_on:
      postgres_reno_regression:
        condition: service_healthy
    entrypoint:
      - ./run-dev.sh
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:MaxRAMPercentage=50 -XshowSettings:vm -XX:MaxRAMFraction=1 -Djava.security.egd=file:/dev/urandom -XX:+UseStringDeduplication
      - ACTIVE_PROFILE=regression
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5099/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=
    links:
      - postgres_reno_regression:postgres_reno_regression
    network_mode: "bridge"

  postgres_reno_regression:
    container_name: "postgres_reno_regression"
    image: postgres:9.6.6
    ports:
      - "5099:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    network_mode: bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
