FROM openjdk:11-jre-slim

WORKDIR /app

ARG API_VERSION="latest"
ENV API_VERSION ${API_VERSION}
ENV PROJECT_NAME="reno"

ADD ./run-dev.sh ./run-dev.sh
RUN sed -i 's/\r$//' run-dev.sh
RUN chmod +x 'run-dev.sh'

ADD /target/${PROJECT_NAME}-0.0.1-SNAPSHOT.jar ${PROJECT_NAME}-0.0.1-SNAPSHOT.jar