Build Docker Image:
  stage: Build
  image: docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      needs:
        - job: "Load Maven"
          artifacts: true
        - job: "Load Config"
          artifacts: true
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "uat"'
      needs:
        - job: "Load Maven"
          artifacts: true
        - job: "Load Config"
          artifacts: true
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "dev"'
      needs:
        - job: "Load Maven"
          artifacts: true
        - job: "Load Config"
          artifacts: true
      when: on_success
    # - if: '$CI_COMMIT_BRANCH == "test"' # TODO: remove
    #   when: on_success
    - when: never
  services:
    - docker:dind
  # needs: # TODO: remove
  #   - job: "Load Maven"
  #     artifacts: true
  #   - job: "Load Config"
  #     artifacts: true
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Logging into ${CI_REGISTRY}"
    - docker login --username gitlab-ci-token --password "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker images
    - docker push --all-tags $CI_REGISTRY_IMAGE
