Build Docker Image:
  stage: Build
  image: docker
  services:
    - docker:dind
  needs:
    - job: "Load Maven"
      artifacts: true
    - job: "Load Config"
      artifacts: true
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Logging into ${CI_REGISTRY}"
    - docker login --username gitlab-ci-token --password "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker images
    - docker push --all-tags $CI_REGISTRY_IMAGE
