ExA:
  extends: .aws-base
  stage: Example
  script:
    - apt-get update && apt-get install -y jq
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set default.region ap-southeast-1
    - aws configure set default.output json
    - export SECRET_STRING=`aws secretsmanager get-secret-value --secret-id ${CI_COMMIT_BRANCH}/${CI_PROJECT_NAME} | jq --raw-output .SecretString `
    - export SECRET_ENV_EC2_PUBLIC_IP_ADDRESS=`echo $SECRET_STRING | jq -r .SECRET_ENV_EC2_PUBLIC_IP_ADDRESS`
    - echo SECRET_ENV_EC2_PUBLIC_IP_ADDRESS=$SECRET_ENV_EC2_PUBLIC_IP_ADDRESS >> build.env
    - echo PROJECT_CONFIG="$SECRET_STRING" >> build.env
  artifacts:
    reports:
      dotenv: build.env

ExB:
  extends: .aws-base
  stage: ExampleDeploy
  before_script:
    - echo $SECRET_ENV_EC2_PUBLIC_IP_ADDRESS
    - echo $PROJECT_CONFIG
  # dependencies:
  #   - ExA
  needs:
    - job: "ExA"
      artifacts: true
  script:
    - echo $SECRET_ENV_EC2_PUBLIC_IP_ADDRESS
    - echo $PROJECT_CONFIG
