Load Config:
  stage: Package
  # needs: ["Unit Test"]
  extends: .aws-base
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      needs: ["Unit Test"]
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "uat"'
      needs: ["Unit Test"]
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "dev"'
      needs: ["Unit Test"]
      when: on_success
      # - if: '$CI_COMMIT_BRANCH == "test"' # TODO: remove
    #   needs: ["Unit Test"]
    #   when: on_success
    - when: never
  script:
    - aws s3 cp s3://${AWS_S3_BUCKET}/rogue.py .
    - aws s3 cp s3://${AWS_S3_BUCKET}/${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}/key_pair.pem .
  artifacts:
    paths:
      - ./rogue.py
      - ./key_pair.pem

Load Maven:
  stage: Package
  needs: ["Unit Test"]
  script: "mvn package -B"
  extends: .mvn-base
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      needs: ["Unit Test"]
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "uat"'
      needs: ["Unit Test"]
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "dev"'
      needs: ["Unit Test"]
      when: on_success
    # - if: '$CI_COMMIT_BRANCH == "test"' # TODO: remove
    #   needs: ["Unit Test"]
    #   when: on_success
    - when: never
  artifacts:
    paths:
      - target/*.jar
