Load Config:
  stage: Package
  # needs: ["Unit Test"]
  extends: .aws-base
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "uat"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: on_success
    - when: never
  script:
    - aws s3 cp s3://${AWS_S3_BUCKET}/rogue.py .
  artifacts:
    paths:
      - ./rogue.py

Load Maven:
  stage: Package
  needs: ["Unit Test"]
  script: "mvn package -B"
  extends: .mvn-base
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "uat"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
    - when: never
  artifacts:
    paths:
      - target/*.jar
